version: '3.8'

services:
  linq-acmecrm-api:
    build: .
    ports:
      - "8200:8200"
    environment:
      - PORT=8200
      - HOST=0.0.0.0
      - JWT_SECRET_KEY=linq-assessment-secret-key-2024
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=30
    volumes:
      - ./frontend:/app/frontend:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8200/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: linq-network
